version: '3'
services:
  brscan:
    build: ./image
    image: brscan4:0.4.10-1
    environment:
      - MODEL=MFC-L2740DW
      - IPADDRESS=192.168.88.200
      - USERNAME=ZOOEY
    network_mode: host
    volumes:
      - scans:/scans
      - ./image/script:/opt/brother/scanner/brscan-skey/script/
    restart: unless-stopped
    stop_signal: SIGHUP

  onedrive:
    # ACHTUN muss interaktiv initialisiert werden  docker-compose run --no-deps onedrive
    image: driveone/onedrive:latest
    restart: unless-stopped
    environment:
      - ONEDRIVE_UID=1001
      - ONEDRIVE_GID=1001
      - ONEDRIVE_VERBOSE=1
    volumes: 
      - ./onedrive_conf:/onedrive/conf
      - scans:/onedrive/data/zooey/Posteingang

volumes:
  scans: